const cursos = [
  'Ciência da Computação',
  'Engenharia de Computação',
  'Sistemas de Informação',
  'Engenharia Civil',
  'Engenharia Elétrica',
  'Engenharia Mecânica',
  'Engenharia Química',
  'Medicina',
  'Direito',
  'Administração',
  'Economia',
  'Psicologia',
  'Pedagogia',
  'Letras',
  'Matemática',
  'Física',
  'Química',
  'Biologia',
  'Arquitetura e Urbanismo',
  'Design',
  'Comunicação Social',
  'Jornalismo',
  'Outros',
];
